export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import localFont from "next/font/local";

const geistMono = localFont({ src: "../../../public/fonts/GeistMonoVF.woff" });
const geistSans = localFont({ src: "../../../public/fonts/GeistVF.woff" });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistSans.className}>{children}</body>
    </html>
  );
}
