// @tourist/layout.js
import Dashboard from "@/components/ui/dashboard";
import { getSession } from "@/lib/session";

import localFont from "next/font/local";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const geistMono = localFont({ src: "../../../public/fonts/GeistMonoVF.woff" });
const geistSans = localFont({ src: "../../../public/fonts/GeistVF.woff" });

import Footer from "@/components/shared/Footer";

export default async function RootLayout({ children }) {
  const Session = await getSession();

  return (
    <body className={geistSans.className}>
      <header>
        <Dashboard
          params={{
            role: "Advertiser",
            id: Session?.user?.id,
          }}
        />
      </header>
      <main>{children}</main>
      <Footer />
    </body>
  );
}
