import localFont from "next/font/local";
import Dashboard from "@/components/ui/dashboard";
import Footer from "@/components/shared/Footer";

import { getSession } from "@/lib/session";

const geistMono = localFont({ src: "../../../public/fonts/GeistMonoVF.woff" });
const geistSans = localFont({ src: "../../../public/fonts/GeistVF.woff" });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }) {
  const Session = await getSession();

  return (
      <body className={geistSans.className}>
        <header>
          <Dashboard
            params={{
              role: "Tourism Governor",
              /*id: "67001e91b4ba61e78487b585"*/ id: Session?.user?.id,
            }}
          />
        </header>
        {children}
        <Footer />
      </body>
  );
}
