import Dashboard from "@/components/ui/dashboard";

import "../globals.css";
import { getSession } from "@/lib/session";
import AuthProvider from "@/providers/SessionProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
  guest,
  admin,
  advertiser,
  seller,
  tourGuide,
  tourismGovernor,
  tourist,
}) {
  const session = await getSession()

  console.log(session)

  return (
    <html lang="en">
      <AuthProvider>
        <body>
          {/* <header>
            <Dashboard params={{ role: "Advertiser" }} />
          </header> */}
          {
            session?.user?.role === 'Tourist' ? tourist :
            session?.user?.role === 'Admin' ? admin :
            session?.user?.role === 'Advertiser' ? advertiser :
            session?.user?.role === 'Seller' ? seller :
            session?.user?.role === 'TourGuide' ? tourGuide :
            session?.user?.role === 'TourismGovernor' ? tourismGovernor :
            session?.user?.role === 'Tourist' ? tourist : guest
          }
        </body>
      </AuthProvider>
    </html>
  );
}
