export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  guest,
  admin,
  advertiser,
  seller,
  tourGuide,
  tourismGovernor,
  tourist,
}) {
  return (
    <html lang="en">
      <body>{tourist}</body>
    </html>
  );
}
