import Footer from "@/components/shared/Footer"
import Dashboard from "@/components/ui/dashboard"
import { getSession } from "next-auth/react"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <Dashboard
          params={{
            role: "Tour Guide",
            /*id: "67001e91b4ba61e78487b585"*/ id: getSession?.user?.id,
          }}
        />
        <main>{children}</main>
        <Footer />
      </html>
    )
  }
  